# You need REST Client extension for VS Code to use this file
# Download at https://aka.ms/vscode/rest-client

GET http://localhost:7071/api/

###

POST http://localhost:7071/api/accounts/
Content-Type: application/json

{
  "user": "sinedied",
  "currency": "$",
  "balance": 50
}

###

GET http://localhost:7071/api/accounts/sinedied

###

DELETE http://localhost:7071/api/accounts/sinedied

###

POST http://localhost:7071/api/accounts/sinedied/transactions
Content-Type: application/json

{
  "date": "2020-07-24",
  "object": "Bought book",
  "amount": -20
}

###

DELETE http://localhost:7071/api/accounts/sinedied/transactions/1b68753f7ae462baf162d5c6b34245d3
